### ISSUE TITLE
Afterburner not working with 2.5.3

### ISSUE THREAD

**Issue by rdifalco** [FasterXML/jackson-module-afterburner#54]
I'm having an issue with afterburner with all modules sync'd on 2.5.3. 

I'm also using the JSR310Module.

I keep getting this exception:

    java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ser.BeanPropertyWriter.getSerializedName()Lcom/fasterxml/jackson/core/SerializableString;
	at com.fasterxml.jackson.module.afterburner.ser.OptimizedBeanPropertyWriter.<init>(OptimizedBeanPropertyWriter.java:45)
	at com.fasterxml.jackson.module.afterburner.ser.ObjectMethodPropertyWriter.<init>(ObjectMethodPropertyWriter.java:14)
	at com.fasterxml.jackson.module.afterburner.ser.PropertyAccessorCollector.addObjectGetter(PropertyAccessorCollector.java:64)
	at com.fasterxml.jackson.module.afterburner.ser.SerializerModifier.findProperties(SerializerModifier.java:133)
	at com.fasterxml.jackson.module.afterburner.ser.SerializerModifier.changeProperties(SerializerModifier.java:49)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:384)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:272)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:217)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:152)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1077)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1037)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:445)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:599)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:93)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:809)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:684)

**Comment by cowtowncoder** [comment]
It still looks like a version incompatibility between Afterburner module and `jackson-databind`.
Return type of that method was changed between 2.3 and 2.4 (2.3 had concrete impl type `SerializedString`), so from the exception it would seem like 2.5.x of Afterburner was running against databind version 2.3 or earlier.

So maybe `jackson-databind` is included as a transitive dependency, not explicitly? Its minor version should match.

**Comment by rdifalco** [comment]
Yes, I was using another library that brought in jackson dependencies under a different name and version. I apologize for the mistake.

**Comment by cowtowncoder** [comment]
No problem, it is an unfortunate incompatibility, and I hope we can minimize these. So it is sort of good to hear of specific cases of specific incompatibilities. Afterburner is bit more fragile than other modules, since it integrates at very low level. Glad you got this working.
